python mxe_parser.py --input ./data/BankAccountPL/bankAccountProduct-Merged.mxe --output DeepLinker/bankAccountPL/bankAccountProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels True --add-info-firstline False --dublicate-node-features 256 --embeddings embeddings.txt
python mxe_parser.py --input ./data/EmailPL/emailProduct-Merged.mxe --output DeepLinker/EmailPL/emailProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels True --add-info-firstline False --dublicate-node-features 256 --embeddings embeddings.txt
python mxe_parser.py --input ./data/SodaVendingMachinePL/svmProduct-Merged.mxe --output DeepLinker/SodaVendingMachinePL/svmProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels True --add-info-firstline False --dublicate-node-features 256 --embeddings embeddings.txt
python mxe_parser.py --input ./data/StudentAttendanceSystemPL/sasProduct-Merged.mxe --output DeepLinker/StudentAttendanceSystemPL/sasProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels True --add-info-firstline False --dublicate-node-features 256 --embeddings embeddings.txt

python mxe_parser.py --input ./data/BankAccountPL/bankAccountProduct-Merged.mxe --output SEAL/bankAccountPL/bankAccountProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels False --add-info-firstline False --embeddings embeddings.txt
python mxe_parser.py --input ./data/EmailPL/emailProduct-Merged.mxe --output SEAL/EmailPL/emailProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels False --add-info-firstline False --embeddings embeddings.txt
python mxe_parser.py --input ./data/SodaVendingMachinePL/svmProduct-Merged.mxe --output SEAL/SodaVendingMachinePL/svmProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels False --add-info-firstline False --embeddings embeddings.txt
python mxe_parser.py --input ./data/StudentAttendanceSystemPL/sasProduct-Merged.mxe --output SEAL/StudentAttendanceSystemPL/sasProduct-Merged --number-of-node-features 1 --as-undirected False --generate-edge-symmetry False --add-node-labels False --add-info-firstline False --embeddings embeddings.txt

